version: '3.4'

services:
  bugtrackerapi:
    image: ${DOCKER_REGISTRY-}bugtrackerapi
    build:
      context: .
      dockerfile: BugTrackerAPI/Dockerfile
    depends_on:
        - db

  db:
    image: postgres:14.1
    ports:
        - 5432:5432 
    volumes:
        - postgre-data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "bugtracker_user"
      POSTGRES_DB: "bugtracker"
  
volumes:
  postgre-data:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '../postgres-data/'